In [2]:
import numpy as np

In [15]:
n = 6
S = np.random.randn(n, n)
S = S.T @ S
S

array([[ 1.46036383,  1.80778558,  0.40624317,  0.57363359, -0.33522611,
         1.2314131 ],
       [ 1.80778558, 16.99516218,  3.24483866, -0.46120257, -0.2301705 ,
         7.72283184],
       [ 0.40624317,  3.24483866,  6.87223665, -2.59780335, -0.7260679 ,
         1.6966011 ],
       [ 0.57363359, -0.46120257, -2.59780335,  6.29994749, -2.19561696,
         1.85842369],
       [-0.33522611, -0.2301705 , -0.7260679 , -2.19561696,  1.70410665,
        -0.24638131],
       [ 1.2314131 ,  7.72283184,  1.6966011 ,  1.85842369, -0.24638131,
         7.16997409]])

In [32]:
SS = S - np.tile(np.mean(S, axis=0), (n, 1))

In [33]:
SS.mean(axis=0)

array([ 1.85037171e-17, -2.96059473e-16, -1.48029737e-16,  3.70074342e-17,
        2.77555756e-17,  1.48029737e-16])

In [16]:
Id = np.eye(n, dtype=float)
J = np.ones((n, n), dtype=float)
C = Id - J / n

Sc = C @ S @ C
Sc

array([[ 1.52341486, -2.1183354 , -0.15601166,  0.91448983,  0.9234198 ,
        -1.08697743],
       [-2.1183354 ,  9.0798692 , -1.30658818, -4.10951833, -2.96069659,
         1.41526931],
       [-0.15601166, -1.30658818,  5.68467595, -2.88225297, -0.09272785,
        -1.24709529],
       [ 0.91448983, -4.10951833, -2.88225297,  6.91860894, -0.65916584,
        -0.18216163],
       [ 0.9234198 , -2.96069659, -0.09272785, -0.65916584,  4.15834744,
        -1.36917696],
       [-1.08697743,  1.41526931, -1.24709529, -0.18216163, -1.36917696,
         2.470142  ]])

In [17]:
D = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        D[i, j] = S[i, i] + S[j, j] - 2.0 * S[i, j]

D

array([[ 0.        , 14.83995486,  7.52011414,  6.61304414,  3.83492271,
         6.16751172],
       [14.83995486,  0.        , 17.3777215 , 24.21751481, 19.15960982,
         8.71947258],
       [ 7.52011414, 17.3777215 ,  0.        , 18.36779084, 10.02847909,
        10.64900853],
       [ 6.61304414, 24.21751481, 18.36779084,  0.        , 12.39528806,
         9.7530742 ],
       [ 3.83492271, 19.15960982, 10.02847909, 12.39528806,  0.        ,
         9.36684335],
       [ 6.16751172,  8.71947258, 10.64900853,  9.7530742 ,  9.36684335,
         0.        ]])

In [18]:
a = np.trace(S)
a

40.50179088180978

In [19]:
b = np.trace(C @ S @C)
b

29.835058391069243

In [20]:
c = np.sum(D)
c

358.0207006928309

In [21]:
c / b

12.0

In [10]:
idx = slice(0, 0)
b_ = b[idx]
b_

array([], dtype=float64)

In [11]:
b_.reshape(3, 2)

ValueError: cannot reshape array of size 0 into shape (3,2)