In [1]:
import numpy as np

In [2]:
n = 5
A = np.random.randn(n, n)
A = A.T @ A
A

array([[ 0.69430722,  0.93367953, -0.15018657, -1.18225324, -0.04784818],
       [ 0.93367953,  5.49542933,  0.80044105, -1.3743059 , -0.02707753],
       [-0.15018657,  0.80044105,  4.51555136,  2.5604538 , -0.85247416],
       [-1.18225324, -1.3743059 ,  2.5604538 ,  4.79990332, -0.89692051],
       [-0.04784818, -0.02707753, -0.85247416, -0.89692051,  2.30934034]])

In [3]:
def cov_center(A):

    Id = np.eye(n, dtype=float)
    J = np.ones((n, n), dtype=float)
    C = Id - J / n
    
    Ac = C @ A @ C
    return Ac

Ac = cov_center(A)
Ac

array([[ 1.28888964,  0.4121684 , -0.88082149, -1.31950656,  0.49927   ],
       [ 0.4121684 ,  3.85782467, -1.04628742, -2.62765276, -0.59605289],
       [-0.88082149, -1.04628742,  2.4596991 ,  1.09798313, -1.63057332],
       [-1.31950656, -2.62765276,  1.09798313,  3.93081426, -1.08163807],
       [ 0.49927   , -0.59605289, -1.63057332, -1.08163807,  2.80899428]])

In [4]:
def var_diff(A):
    d = np.array([np.diag(A)]).reshape(n, 1)
    e = np.ones((n, 1))
    
    S = d @ e.T + e @ d.T - 2.0 * A
    return S

S = var_diff(A)
S

array([[ 0.        ,  4.3223775 ,  5.51023172,  7.85871702,  3.09934392],
       [ 4.3223775 ,  0.        ,  8.4100986 , 13.04394445,  7.85892473],
       [ 5.51023172,  8.4100986 ,  0.        ,  4.19454709,  8.52984003],
       [ 7.85871702, 13.04394445,  4.19454709,  0.        ,  8.90308468],
       [ 3.09934392,  7.85892473,  8.52984003,  8.90308468,  0.        ]])

In [5]:
np.sum(S) / (2.0 * n * np.trace(Ac))

1.0

In [7]:
e = np.linalg.eigh(Ac)[0]
e

array([-1.35810813e-15,  1.00459258e+00,  1.59692898e+00,  4.13203484e+00,
        7.61266555e+00])

In [13]:
e = np.linalg.eigh(S)[0]
e

array([-15.2445879 ,  -8.31108782,  -3.67682394,  -2.18778844,
        29.42028811])

In [11]:
Q = -0.5 * cov_center(S)

e = np.linalg.eigh(Q)[0]
e

array([-4.69687463e-16,  1.00459258e+00,  1.59692898e+00,  4.13203484e+00,
        7.61266555e+00])